#!/usr/bin/env python

import sys
import argparse
import numpy as np
import pandas as pd

import tensorflow as tf

import tensorflow.compat.v1.keras.backend as K
tf.compat.v1.disable_eager_execution()


def run_train(args):
    print("do stuff")



def run_gen(args):
    print("do stuff")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
                    prog = 'Synthesis',
                    description = 'Generate Synthetic samples')
    
    subparsers = parser.add_subparsers(title="subcommand")

    train_parser = subparsers.add_parser('train')
    train_parser.set_defaults(func=run_train)

    train_parser = subparsers.add_parser('gen')
    train_parser.set_defaults(func=run_gen)


    args = parser.parse_args()

    if not hasattr(args, "func"):
        parser.print_help(sys.stderr)
        sys.exit(1)

    func = args.func
    e = func(args)
    sys.exit(e)